In [1]:
import pickle
import numpy as np

In [2]:
pipe_decisiontree = pickle.load(open('pipe_decisiontree.pkl','rb'))
pipe_lightgbm = pickle.load(open('pipe_lightgbm.pkl','rb'))

In [3]:
# Assume user input
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [4]:
pipe_decisiontree.predict(test_input)

C:\Users\Nihar\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\Nihar\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [5]:
pipe_lightgbm.predict(test_input)

C:\Users\Nihar\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\Nihar\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0], dtype=int64)