In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import *

from sklearn.datasets import load_iris

In [2]:
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
df = pd.DataFrame(load_iris().data,columns=load_iris().feature_names)
df['target'] = load_iris().target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [4]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

log = LogisticRegression()
dt = DecisionTreeClassifier()

log.fit(X_train,y_train)
dt.fit(X_train,y_train)

y_pred = log.predict(X_test)
y_pred1 = dt.predict(X_test)


print(f'Accuracy of LogisticRegression : {accuracy_score(y_test,y_pred)}')
print(f'Accuracy of DecisionTree : {accuracy_score(y_test,y_pred1)}')

Accuracy of LogisticRegression : 0.9666666666666667
Accuracy of DecisionTree : 0.9333333333333333


In [6]:
print(f'confusion_matrix of LogisticRegression : \n {confusion_matrix(y_test,y_pred)}')
print('\n')
print(f'confusion_matrix of DecisionTree : \n {confusion_matrix(y_test,y_pred1)}')

confusion_matrix of LogisticRegression : 
 [[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]


confusion_matrix of DecisionTree : 
 [[14  0  0]
 [ 0  7  1]
 [ 0  1  7]]


In [7]:
print('confusion_matrix of LogisticRegression : ')
pd.DataFrame(confusion_matrix(y_test,y_pred),columns=[0,1,2])



confusion_matrix of LogisticRegression : 


0  1  2
0  14  0  0
1   0  7  1
2   0  0  8

In [8]:
print('confusion_matrix of DecisionTree : ')
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=[0,1,2])

confusion_matrix of DecisionTree : 


0  1  2
0  14  0  0
1   0  7  1
2   0  1  7

# Logistic Regession

In [9]:
print('Logistic Regression'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred,average=None))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred,average=None))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred,average=None))

               Logistic Regression                
__________________________________________________
Confusion Matrix : 
     0  1  2
0  14  0  0
1   0  7  1
2   0  0  8
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Accuracy :  0.9666666666666667
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Precision :  [1.         1.         0.88888889]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Recall :  [1.    0.875 1.   ]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
F1 score :  [1.         0.93333333 0.94117647]


In [10]:
print('Logistic Regression'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred,average='macro'))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred,average='macro'))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred,average='macro'))

               Logistic Regression                
__________________________________________________
Confusion Matrix : 
     0  1  2
0  14  0  0
1   0  7  1
2   0  0  8
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Accuracy :  0.9666666666666667
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Precision :  0.9629629629629629
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Recall :  0.9583333333333334
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
F1 score :  0.9581699346405229


In [11]:
print('Logistic Regression'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred,average='weighted'))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred,average='weighted'))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred,average='weighted'))

               Logistic Regression                
__________________________________________________
Confusion Matrix : 
     0  1  2
0  14  0  0
1   0  7  1
2   0  0  8
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Accuracy :  0.9666666666666667
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Precision :  0.9703703703703703
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Recall :  0.9666666666666667
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
F1 score :  0.9665359477124185


In [12]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



# Decision tree

In [13]:
print('Decision tree'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred1))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred1))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred1,average=None))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred1,average=None))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred1,average=None))

                  Decision tree                   
__________________________________________________
Confusion Matrix : 
     0  1  2
0  14  0  0
1   0  7  1
2   0  1  7
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Accuracy :  0.9333333333333333
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Precision :  [1.    0.875 0.875]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Recall :  [1.    0.875 0.875]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
F1 score :  [1.    0.875 0.875]


In [14]:
print('Decision tree'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred1))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred1))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred1,average='macro'))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred1,average='macro'))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred1,average='macro'))

                  Decision tree                   
__________________________________________________
Confusion Matrix : 
     0  1  2
0  14  0  0
1   0  7  1
2   0  1  7
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Accuracy :  0.9333333333333333
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Precision :  0.9166666666666666
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Recall :  0.9166666666666666
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
F1 score :  0.9166666666666666


In [15]:
print('Decision tree'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred1))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred1))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred1,average='weighted'))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred1,average='weighted'))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred1,average='weighted'))

                  Decision tree                   
__________________________________________________
Confusion Matrix : 
     0  1  2
0  14  0  0
1   0  7  1
2   0  1  7
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Accuracy :  0.9333333333333333
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Precision :  0.9333333333333333
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Recall :  0.9333333333333333
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
F1 score :  0.9333333333333333


In [16]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.88      0.88      0.88         8
           2       0.88      0.88      0.88         8

    accuracy                           0.93        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.93      0.93      0.93        30

