In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes

https://scikit-learn.org/stable/modules/model_evaluation.html

In [9]:
X,y = load_diabetes(return_X_y=True)
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [10]:
X.shape

(442, 10)

In [5]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
y.shape

(442,)

In [11]:
df = pd.DataFrame(X,columns=['age (age in years)','sex','bmi(body mass index)','bp(average blood pressure)','s1 tc( total serum cholesterol)','s2 idl(low-density lipoproteins)'
                            ,'s3 hdl( high-density lipoproteins)','s4 tch(total cholesterol / HDL)','s5 ltg (possibly log of serum triglycerides level)','s6 glu (blood sugar level)'])

df['target'] = y

df.head()

age (age in years)       sex  bmi(body mass index)  \
0            0.038076  0.050680              0.061696   
1           -0.001882 -0.044642             -0.051474   
2            0.085299  0.050680              0.044451   
3           -0.089063 -0.044642             -0.011595   
4            0.005383 -0.044642             -0.036385   

   bp(average blood pressure)  s1 tc( total serum cholesterol)  \
0                    0.021872                        -0.044223   
1                   -0.026328                        -0.008449   
2                   -0.005671                        -0.045599   
3                   -0.036656                         0.012191   
4                    0.021872                         0.003935   

   s2 idl(low-density lipoproteins)  s3 hdl( high-density lipoproteins)  \
0                         -0.034821                           -0.043401   
1                         -0.019163                            0.074412   
2                         -0.034194                           -0.032356   
3                          0.024991                           -0.036038   
4                          0.015596                            0.008142   

   s4 tch(total cholesterol / HDL)  \
0                        -0.002592   
1                        -0.039493   
2                        -0.002592   
3                         0.034309   
4                        -0.002592   

   s5 ltg (possibly log of serum triglycerides level)  \
0                                           0.019908    
1                                          -0.068330    
2                                           0.002864    
3                                           0.022692    
4                                          -0.031991    

   s6 glu (blood sugar level)  target  
0                   -0.017646   151.0  
1                   -0.092204    75.0  
2                   -0.025930   141.0  
3                   -0.009362   206.0  
4                   -0.046641   135.0

# Using Sklearn Linear Regression

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

print((X_train.shape,X_test.shape))

((353, 10), (89, 10))


In [14]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [15]:
y_pred = lr.predict(X_test)

In [17]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print('MAE :', mean_absolute_error(y_test,y_pred))
print('MSE :', mean_squared_error(y_test,y_pred))
print('RMSE :', np.sqrt(mean_squared_error(y_test,y_pred)))
print('R2 Score :', r2_score(y_test,y_pred))

adjusted_r2_score = 1- ((1-r2_score(y_test,y_pred))*(y_test.shape[0]-1))/(y_test.shape[0]-1-X_test.shape[1])
print('Adjusted r2 Score :', adjusted_r2_score)

MAE : 45.21292481299676
MSE : 3094.4295991207023
RMSE : 55.62759745954073
R2 Score : 0.4399387660024645
Adjusted r2 Score : 0.3681360436950881


In [18]:
lr.coef_

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [19]:
lr.intercept_

151.88334520854633

# Making own class Linear Regression

In [41]:
class LinearRegression():
    
    def __init__(self):
        self.coef_=None
        self.intercept_=None
        
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)
        
        betas= np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
        
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_ 

In [42]:
lr = LinearRegression()

In [43]:
lr.fit(X_train,y_train)

In [44]:
y_pred = lr.predict(X_test)

In [45]:
print('MAE :', mean_absolute_error(y_test,y_pred))
print('MSE :', mean_squared_error(y_test,y_pred))
print('RMSE :', np.sqrt(mean_squared_error(y_test,y_pred)))
print('R2 Score :', r2_score(y_test,y_pred))

adjusted_r2_score = 1- ((1-r2_score(y_test,y_pred))*(y_test.shape[0]-1))/(y_test.shape[0]-1-X_test.shape[1])
print('Adjusted r2 Score :', adjusted_r2_score)

MAE : 45.21292481299679
MSE : 3094.429599120706
RMSE : 55.627597459540766
R2 Score : 0.43993876600246384
Adjusted r2 Score : 0.36813604369508746


In [46]:
lr.coef_

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [47]:
lr.intercept_

151.8833452085463